### ISSUE TITLE
Turn on/off each mcp port or all module

### ISSUE THREAD

**Issue by Haysar2019** [bakercp/MCP3XXX#1]
Hi, this is a question, as I said with Christopher. I would like to know if is possible control the mcp module, example, turn on/off the whole module or turn on/off each A/D port?
I'm using the MCP3008 module, but actually I'm using only 3 sensors connected on mcp3008 and I would like to send power only for these sensors and not for all ports and send the power only I need and not all time. I need this have more control about on mcp 3008 module to reduce battery consumption.
Thanks,
Haysar Lelis

**Comment by bakercp** [comment]
Hi there, according to the data sheet, you can't turn individual ports on and off.  So if you want to use less current, then you should just use a smaller module -- e.g. it sounds like the MCP3004 would be a better fit for your design.  

That said, the chip already goes into low-power mode between reads, because when the CS pin goes high, it goes into standby mode (which this addon already does).

<img width="384" alt="MCP3004_3008_2_7V_4-Channel_8-Channel_10-bit_A_D_Converters_with_SPI_Serial_Interface_-_21295c_pdf" src="https://user-images.githubusercontent.com/300484/62840975-ce482a00-bc67-11e9-97e1-48e8103cbc49.png">
